### ISSUE TITLE
TC wand in Transmutation Table

### ISSUE THREAD

**Issue by jerjerje** [DrasticDemiseFTBPacks/Banished#121]
I put my thaumcraft wand in my transmutation table and when I took it out, I was kicked from my Server and I can't join again. Does anyone know how to fix this?

**Comment by jerjerje** [comment]
The game crashes if I do that in Singleplayer. Here is the crashreport:java.lang.NullPointerException: Ticking player
    at taintedmagic.common.lib.handler.TMEventHandler.updateAttackDamage(TMEventHandler.java:112)
    at taintedmagic.common.lib.handler.TMEventHandler.livingTick(TMEventHandler.java:74)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_654_TMEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(Unknown Source)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at taintedmagic.common.lib.handler.TMEventHandler.updateAttackDamage(TMEventHandler.java:112)
    at taintedmagic.common.lib.handler.TMEventHandler.livingTick(TMEventHandler.java:74)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_654_TMEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(Unknown Source)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 3716
    Entity Name: jerjerje
    Entity's Exact location: 42,48, 51,54, 145,65
    Entity's Block location: World: (42,51,145), Chunk: (at 10,3,1 in 2,9; contains blocks 32,0,144 to 47,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0,00, -0,30, 0,00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@49ee0375
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1324590696 bytes (1263 MB) / 2199388160 bytes (2097 MB) up to 4330618880 bytes (4130 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4646m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 109 mods loaded, 108 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   AM2-Preloader{0.0.3} [AMCore](minecraft.jar) 
    UCHIJAAAA   Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   ivtoolkit{IvToolkit} [1.2](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.106} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.106-universal.jar) 
    UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJAAAA   WitchingGadgetsCore{1.1.10} [Witching Gadgets Core](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   debug{1.0} [debug](denseores-1.6.2.jar) 
    UCHIJAAAA   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar) 
    UCHIJAAAA   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJAAAA   StartingInventory{1.7.10.r03} [StartingInventory]([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
    UCHIJAAAA   AccidentallyCircumstantialEvents{1.7.1} [Accidentally Circumstantial Events](accidentallycircumstantialevents-1.7.1.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   arsmagica2{1.4.0.009} [Ars Magica 2](AM2-1.4.0.009-Dev.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   AromaBackup{0.0.0.6} [AromaBackup](AromaBackup-1.7.10-0.0.0.6.jar) 
    UCHIJAAAA   AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.0.0.6.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   aura{unspecified} [Aura Cascade](AuraCascade-557.jar) 
    UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   Automagy{0.27.1} [Automagy](Automagy-1.7.10-0.27.1.jar) 
    UCHIJAAAA   BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCHIJAAAA   BiomeTweaker{2.0.180} [BiomeTweaker](BiomeTweaker-1.7.10-2.0.180.jar) 
    UCHIJAAAA   Botania{r1.8-248} [Botania](Botania r1.8-248.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAAAA   kegare.caveworld{1.9.7} [Caveworld](Caveworld_1.7.10-v1.9.7.jar) 
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   customitems{1.0.9b} [Meta Mod: Custom Items](customitems-1.0.9_beta_1.7.10.jar) 
    UCHIJAAAA   dldungeonsjdg{1.8.5} [Doomlike Dungeons](DoomlikeDungeons-1.8.5-MC1.7.10.jar) 
    UCHIJAAAA   DynamicLights{1.3.8} [Dynamic Lights](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   ESM{10.0.146} [Epic Siege Mod](EpicSiegeMod-10.0.146.jar) 
    UCHIJAAAA   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJAAAA   ForbiddenMagic{1.7.10-0.573} [Forbidden Magic](Forbidden Magic-1.7.10-0.573.jar) 
    UCHIJAAAA   gadomancy{1.0.6.1} [Gadomancy](gadomancy-1.7.10-1.0.6.3.jar) 
    UCHIJAAAA   GuardianChest{1.7.10} [Guardian Chest](guardianchest-1.6.jar) 
    UCHIJAAAA   HardcoreQuesting{4.4.4} [Hardcore Questing Mode](HQM-The Journey-4.4.4.jar) 
    UCHIJAAAA   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.7.10-5.1.3-unlimited.jar) 
    UCHIJAAAA   launchgui{1.7.10-2.0-17} [LaunchGUI](LaunchGui-1.7.10-2.0-17-client.jar) 
    UCHIJAAAA   Lockdown{2.0.0} [Lockdown](Lockdown-universal-1.7.2-2.0.0.0.jar) 
    UCHIJAAAA   lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJAAAA   mobinhibitor{1.7.10-1.0} [Mob Inhibitor](mobinhibitor-1.7.10-1.0.jar) 
    UCHIJAAAA   modtweaker2{0.9.2} [Mod Tweaker 2](ModTweaker2-0.9.3.jar) 
    UCHIJAAAA   NaturalAbsorption{1.2.1} [Natural Absorption](NaturalAbsorption-1.7.10-1.2.1.jar) 
    UCHIJAAAA   NEIAddons{1.12.11.36} [NEI Addons](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.0.11} [NEI Integration](NEIIntegration-MC1.7.10-1.0.11.jar) 
    UCHIJAAAA   NodalMechanics{1.7.10R1.0} [NodalMechanics](NodalMechanics-1.7-1.0-7.jar) 
    UCHIJAAAA   PerfectSpawn{1.1} [Perfect Spawn](PerfectSpawn-1.1.jar) 
    UCHIJAAAA   ProjectE{1.7.10-PE1.9.5} [ProjectE](ProjectE-1.7.10-PE1.9.5.jar) 
    UCHIJAAAA   RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHIJAAAA   ResourceLoader{1.2} [Resource Loader](ResourceLoader-1.2.jar) 
    UCHIJAAAA   SilentGems{@VERSION@} [Silent's Gems](SilentGems-1.7.10-1.2.07b-84.jar) 
    UCHIJAAAA   SpecialAI{1.1.1} [Special AI](SpecialAI-1.7.10-1.1.1.jar) 
    UCHIJAAAA   SpecialMobs{3.2.1} [Special Mobs](SpecialMobs-1.7.10-3.2.1.jar) 
    UCHIJAAAA   sprinkles_for_vanilla{1.2.10} [sprinkles_for_vanilla](sprinklesforvanilla-1.7.10-1.2.10.jar) 
    UCHIJAAAA   squidless{0.6.1} [Squidless](squidless-1.7.10-0.6.1.jar) 
    UCHIJAAAA   StorageDrawers{1.7.10-1.7.6} [Storage Drawers](StorageDrawers-1.7.10-1.7.6.jar) 
    UCHIJAAAA   TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar) 
    UCHIJAAAA   ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) 
    UCHIJAAAA   thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHIJAAAA   ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-37.jar) 
    UCHIJAAAA   ThaumicHorizons{1.1.9} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.9.jar) 
    UCHIJAAAA   thaumicinfusion{4.32} [Thaumic Infusion](ThaumicInfusion-4.32.jar) 
    UCHIJAAAA   TravellersGear{1.16.6} [Traveller's Gear](TravellersGear-1.7.10-1.16.6.jar) 
    UCHIJAAAA   UtilityMobs{3.1.1} [Utility Mobs](UtilityMobs-1.7.10-3.1.1.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCHIJAAAA   wildcaves3{0.4.3.6} [Wild Caves 3](WildCaves3-0.4.3.6%281.7.2%29.jar) 
    UCHIJAAAA   WitchingGadgets{1.1.10} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.10.jar) 
    UCHIJAAAA   yampst{1.3.5} [YAMPST](Yampst-Banished-1.2.4.jar) 
    UCHIJAAAA   aobd{2.7.1} [Another One Bites The Dust](AOBD-2.7.1.jar) 
    UCHIJAAAA   denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
    UD  BiomeTweakerCore{2.0.180} [BiomeTweaker Core](minecraft.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    CoFHCore: -[1.7.10]3.0.3-303
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['jerjerje'/3716, l='New World', x=42,48, y=51,54, z=145,65]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
