### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by FranklinShack** [DrasticDemiseFTBPacks/Banished#31]
Whenever I try to launch the game, I get this on the log:

Logging in...
Beginning authlib authentication attempt
successfully created YggdrasilAuthenticationService
Login complete.
Checking local assets file, for MC version1.7.10 Please wait! 
Setting up native libraries for Banished v 0.0.6 MC 1.7.10
Syncing Assets:
Java Path: C:\Program Files\Java\jre1.8.0_45\bin\javaw.exe
Pack: Banished 1.7.10
Setting MinMemory to 256
Setting MaxMemory to 6144
[16:57:31] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:57:31] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_45]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.11.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_45]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by DrasticDemise** [comment]
Try deleting it and force updating.

**Comment by FranklinShack** [comment]
Done that twice, still receiving the issue

**Comment by DrasticDemise** [comment]
Have you made any changes to java or the launcher since the last update and can you relaunch older versions?

**Comment by FranklinShack** [comment]
I have not done anything to java or the launcher, and I can launch older versions

**Comment by DrasticDemise** [comment]
Still having issues?

**Comment by FranklinShack** [comment]
Yep

**Comment by DrasticDemise** [comment]
I will be updating today so it may fix the issue for you. Try changing the server that the FTB launcher uses

**Comment by FranklinShack** [comment]
Alright, thanks! I'll try again after the update

**Comment by DrasticDemise** [comment]
New update is up.
