### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by FranklinShack** [DrasticDemiseFTBPacks/Banished#39]
Still getting this when I try to launch

MCVersion: 1710
Logging in...
Beginning authlib authentication attempt
successfully created YggdrasilAuthenticationService
Login complete.
Checking local assets file, for MC version1.7.10 Please wait! 
Setting up native libraries for Banished v 0.0.7 MC 1.7.10
Syncing Assets:
Java Path: C:\Program Files\Java\jre1.8.0_45\bin\javaw.exe
Pack: Banished 1.7.10
Setting MinMemory to 256
Setting MaxMemory to 12239
[11:23:49] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[11:23:49] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45]
    at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by DrasticDemise** [comment]
At this point it isn't a problem inherent with the pack but the launcher itself. Try changing your java version and the server download location from the launcher.

**Comment by FranklinShack** [comment]
Alright

**Comment by DrasticDemise** [comment]
Force updating solved a launch problem for me.

**Comment by FranklinShack** [comment]
Force updating solved the issue
